style_edition = "2024"
use_small_heuristics = "Max"
merge_derives = false
group_imports = "StdExternalCrate"
imports_granularity = "Module"
use_field_init_shorthand = true
max_width = 100
wrap_comments = true
comment_width = 100
reorder_imports = true
reorder_modules = true
format_macro_matchers = true
format_macro_bodies = true
normalize_doc_attributes = true
empty_item_single_line = false